# get all users
###
GET http://localhost:5000/api/v1/users

# register user
###
POST http://localhost:5000/api/v1/users/register
Content-Type: application/json

{
    "name": "Yassin Kassem",
    "email": "yassin63@example.com",
    "password": "password"
}

# login user
###
POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
    "email": "yassin63@example.com",
    "password": "password123"
}


# Auth 
###
GET http://localhost:5000/api/v1/auth

# Logout
###
GET http://localhost:5000/api/v1/users/logout

# forgot password
###
POST http://localhost:5000/api/v1/users/forgetPassword
Content-Type: application/json

{
    "email": "yassin63@example.com",
    "newPassword": "password123"
}

# get user by id
###
GET http://localhost:5000/api/v1/users/67fd6b50ab7843d3f6ce13c7

# update user role
###
PUT http://localhost:5000/api/v1/users/67fd6b50ab7843d3f6ce13c7
Content-Type: application/json

{
    "role" : "System Admin" 
}

# delete user
###
DELETE http://localhost:5000/api/v1/users/67fd68fd0663cf235ad9e697
