# get all users
###
GET http://localhost:5000/api/v1/users

# register user
###
POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
    "name": "malek khaled",
    "email": "malooka@example.com",
    "password": "password"
}

# login user
###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
    "email": "yassin63@example.com",
    "password": "password123"
}


# Auth 
###
GET http://localhost:5000/api/v1/auth

# Logout
###
GET http://localhost:5000/api/v1/users/logout

# forgot password
###
POST http://localhost:5000/api/v1/users/forgetPassword
Content-Type: application/json

{
    "email": "malooka@example.com",
    "newPassword": "password123"
}

# get user by id
###
GET http://localhost:5000/api/v1/users/67fd6b50ab7843d3f6ce13c7

# update user role
###
PUT http://localhost:5000/api/v1/users/67fd6b50ab7843d3f6ce13c7
Content-Type: application/json

{
    "role" : "System Admin" 
}

# delete user
###
DELETE http://localhost:5000/api/v1/users/67fd68fd0663cf235ad9e697

# create event
###
POST http://localhost:5000/api/v1/events
Content-Type: application/json

{
  "title": "Summer Music Festival",
  "description": "Open air music festival with multiple stages",
  "date": "2025-07-20T16:00:00Z",
  "location": "Central Park, New York",
  "category": "concert",
  "ticketPricing": 129.50,
  "totalTicketsAvailable": 10000,
  "remainingTickets": 10000
}

# get all events
###
GET http://localhost:5000/api/v1/events/all

# delete event
###
DELETE http://localhost:5000/api/v1/events/68011d7b6db61dfd4f380ea7
